wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.14
    code_path: code/finetuning_new.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      4: 3.7.9
      5: 0.10.14
batch_size:
  desc: null
  value: 2
ce_loss_only:
  desc: null
  value: true
control_token_weight:
  desc: null
  value: 1.0
d_model:
  desc: null
  value: 512
distance:
  desc: null
  value: medium
eos_weight:
  desc: null
  value: 1
epochs:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.0001
lr_reset:
  desc: null
  value: true
nhead:
  desc: null
  value: 8
num_encoder_layers:
  desc: null
  value: 4
span_lengths:
  desc: null
  value: 3
span_ratio_jointly:
  desc: null
  value: 0.5
use_new_data:
  desc: null
  value: false
